Make `Download File` to download the file instead of Preview
Codeinwp/woocommerce-product-addon pull request #343
Opened 2024-08-30 12:20 UTC by Soare-Robert-Daniel

### Summary

Refactored the `Download File` into a button with download functionality and layout improvments.

### Will affect visual aspect of the product

YES

### Screenshots 

#### Before

![image](https://github.com/user-attachments/assets/b222ced6-ada3-4a2c-baa4-3e39ae8225ca)

#### After

![image](https://github.com/user-attachments/assets/9fca34d1-196e-47f4-b0b9-8313344cda07)

### Test instructions

- Make a Group Field with an Input Field, then attach it to a product.
- Go to the cart and buy the product along with the uploaded files
- Check the order on the Order Page.
- Click to download the file.

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [ ] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [ ] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [ ] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [ ] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [ ] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/woocommerce-product-addon/issues/280

2024-08-30 13:09 UTC, HardeepAsrani approved these changes

2024-08-30 14:46 UTC, AndreeaCristinaRadacina commented
@Soare-Robert-Daniel looks good; no issues. However, here are my findings:

- when clicking on the image, it opens the whole page, and you need to click on the browser arrow to return. Can we open it as a lightbox with an exit on esc/clicking outside the image, or open it in a new tab? (if you also consider it valuable)

- when the user uploads a file, whether you click on the Download file button or on the file icon, the same thing happens: the file is downloaded (different from what happens in the image case). 

<img width="659" alt="image" src="https://github.com/user-attachments/assets/b51ff99e-3faf-4d08-8452-6cf5da40f619">

2024-09-02 09:19 UTC, Soare-Robert-Daniel commented
@AndreeaCristinaRadacina, I do not get the `or on the file icon`. If you upload something other than an image, the browser will download the file because it can not do the preview.

One idea is to exclude non-image files for having a link preview attached to them.

This is the current behavior. 


https://github.com/user-attachments/assets/3c377728-a87e-4383-9a4a-072c3e1a0927

2024-09-03 09:06 UTC, AndreeaCristinaRadacina commented
Hey @Soare-Robert-Daniel, 

For the above observation, I prepared a video - https://vertis.d.pr/v/VrDoIN

2024-09-03 09:23 UTC, Soare-Robert-Daniel commented
@AndreeaCristinaRadacina, thanks for the video. I will allow clicking on the icon to preview only for images, to not have two things that do the same things.

2024-09-03 09:28 UTC, AndreeaCristinaRadacina commented
@Soare-Robert-Daniel great, that sounds good.

2024-09-03 10:57 UTC, AndreeaCristinaRadacina commented
@Soare-Robert-Daniel, thank you for applying the changes! It works as expected now.

2024-09-03 16:01 UTC, carlalexander requested changes
Just a few small things here. Looks good otherwise 🙌

2024-09-03 16:01 UTC, carlalexander commented on inc/functions.php
> +		}
I think I'd rework this because the `image` html tag is the same in both cases. I always think it's better to avoid duplicating that type of code since it makes easy for bugs to slip in if you need to make changes.

I'd maybe just do something like: 

```php
if ( $is_image_file ) {
			$order_html .= '<a target="_blank" href="' . esc_url( $ppom_file_url ) . '">';
}

$order_html .= '<img class="img-thumbnail" style="width:' . esc_attr( ppom_get_thumbs_size() ) . '" src="' . esc_url( $ppom_file_thumb_url ) . '">';

if ( $is_image_file ) {
			$order_html .= '<\a>';
}
```

2024-09-03 16:01 UTC, carlalexander commented on inc/functions.php
> +		if( $is_image_file ) {
Need a space after `if`

2024-09-03 16:01 UTC, carlalexander commented on inc/functions.php
> +
Why we need three lines here?

2024-09-16 11:28 UTC, merged