Readme
Codeinwp/woocommerce-product-addon pull request #94
Opened 2023-02-12 18:55 UTC by mskapusuz

### Summary

* Pre-sale question URL added (is redirected to the https://themeisle.com/contact/?utm_source=wordpress.org&utm_medium=product&utm_campaign=about-us)
* Demo URLs of the PPOM Free Inputs were updated.
* New demo URLs added for PPOM Pro features.
 
### Will affect visual aspect of the product

NO

### Screenshots

### Test instructions

-
-

Closes #77 .

2023-02-12 18:57 UTC, mskapusuz commented
@selul could you please review the query params of the pre-sale URL? (https://themeisle.com/contact/?utm_source=wordpress.org&utm_medium=product&utm_campaign=about-us)

2023-02-13 08:33 UTC, selul commented
@mskapusuz the referenced issue is wrong, can you adjust it? 

Regarding UTMs you can use the same values/pattern as `tsk_utmify` function, I saw that the free vs pro also has a wrong utm too. 

Also, why is the pre-sales link something that we want to add? I would revert that for now.

2023-02-13 08:33 UTC, selul requested changes
@mskapusuz the referenced issue is wrong, can you adjust it?

2023-02-13 08:33 UTC, selul commented on readme.txt
> +[See All PRO Features](https://themeisle.com/plugins/ppom-pro/upgrade/?utm_source=themeisle&utm_medium=product&utm_campaign) - [Demos](https://demo-ppom-lite.vertisite.cloud/) - [Ask a Pre-sale Quest
Regarding UTMs you can use the same values/pattern as `tsk_utmify` function, I saw that the free vs pro also has a wrong utm too. 

Also, why is the pre-sales link something that we want to add? I would revert that for now.

2023-02-13 11:33 UTC, selul approved these changes

2023-02-13 11:34 UTC, merged